### ISSUE TITLE
Requesting permissions makes the app crash on a physical device. (dev client)

### ISSUE THREAD

**Issue by thebiltheory** [jamsch/expo-speech-recognition#24]
Perhaps I'm doing something wrong but I made sure to follow the doc. 

The app crashes on a **physical** device every time I run `requestPermissionsAsync`.

Here is a simple implementation of a screen.
I stripped everything from the screen to isolate the issue. 
<img width="514" alt="Screenshot 2024-09-25 at 6 43 14 PM" src="https://github.com/user-attachments/assets/97d1fdbc-ec57-45b6-825d-707f942f88f5">

Permissions are also well configured in `app.json`.

Am I missing something?

**Comment by jamsch** [comment]
Hey @thebiltheory!, here's a few things you might want to check:

- Whether you've ran another development build of your app after installing this package (`npx expo run:android` or `npx expo run:ios`). As this package contains native Swift & Kotlin code, you'll need to run this once so that the app is bundled with the native code.
- Whether your project has Expo as a dependency. This project uses Expo APIs from their permissions system to request permissions.

If those don't work, could you provide me the following:

- Wrapping the `requestPermissionsAsync()` in a try/catch, and then console.log the error, and paste it here
- Whether you're running on Android/iOS and what version

**Comment by thebiltheory** [comment]
Hey @jamsch, 
Thanks for the fast response!! 

- ✅ I always running `expo run:ios`
- ✅ Got `expo` as a dependency.

Wrapping it in a `try/catch` doesn't work. The app closes immediately. It's really hard to tell what causes the issue. 

I'm running ios 18 tho.

**Comment by jamsch** [comment]
@thebiltheory That looks like the app wasn't built with the config plugin. Have you added that in to your app.json? You can copy the contents from the installation step 2 on the readme. It's also likely why expo-av wasn't working for you either. You also may need to run a fresh prebuild (`npx expo prebuild --clean`) to regenerate the android/iOS folders with the config from app.json.

**Comment by thebiltheory** [comment]
@jamsch I did! I have also prebuild the app many times 

It was working with ios17 tho. 

<img width="819" alt="Screenshot 2024-09-26 at 9 50 55 AM" src="https://github.com/user-attachments/assets/26304ceb-cb90-4b17-803a-8a1da735a0da">

<img width="811" alt="Screenshot 2024-09-26 at 9 51 18 AM" src="https://github.com/user-attachments/assets/85794970-1c9a-44ea-b4c7-645ff963e4ae">

**Comment by jamsch** [comment]
@thebiltheory Very strange. Just to confirm when you run the prebuild, does your app include the permissions in `ios/[app_name]/Info.plist`? (also small nit: you've got `expo-asset` there twice)

**Comment by thebiltheory** [comment]
I feel stup*d.😂  Removing `expo-asset` did the trick! 

Thanks for being my rubber duck @jamsch. 
![image](https://github.com/user-attachments/assets/0424601a-9b27-4398-9493-2c63ba83232d)

Take aways:
1. Granularly double check configuration.
2. Be more cautious during the rebase of a branch.

**Comment by thebiltheory** [comment]
Fixed.
