### ISSUE TITLE
Request to Add Library to React Native Directory

### ISSUE THREAD

**Issue by SufianBabri** [jamsch/expo-speech-recognition#27]
This is an excellent library that I believe would benefit many developers.

I suggest submitting it to the [React Native Directory](https://github.com/react-native-community/directory) to help it gain more visibility and traction. Adding it there will make it easier for developers to discover and integrate this useful library into their projects.

**Comment by jamsch** [comment]
Hey @SufianBabri, thank you for reminding me, I really should put it there!  I've been keeping this package a bit under wraps so that I can roll out quick API revisions and releases without worrying about semver. But right now the package is getting to a state where it's pretty much ready for public use. It's currently being used in a large production app for the last few months with no issues.

**Comment by jamsch** [comment]
All done!
