### ISSUE TITLE
Empty results when using the Web SpeechRecognition API

### ISSUE THREAD

**Issue by abddeen** [jamsch/expo-speech-recognition#3]
@jamsch I tried the two approaches, hook vs web speech recognition api, and the latter is coming back with empty results.

See this video for details:

https://github.com/user-attachments/assets/c0b2ffb4-65aa-4129-b0a8-63e41d34b2a9

**Comment by jamsch** [comment]
@abddeen Looks like the results aren't properly serialized when calling `Array.from(event.results)`. I pushed out `v0.1.6`, see if that works.

**Comment by abddeen** [comment]
@jamsch Nice, i'm getting results now. But I noticed they are typed as an indexed object as opposed to any array:

<img width="929" alt="image" src="https://github.com/user-attachments/assets/e116da6b-bf99-4721-9ec5-09790ad37d6c">

Compared to hook results:
<img width="815" alt="image" src="https://github.com/user-attachments/assets/67ed4dc6-31df-4dab-8830-dbc1cd448202">

**Comment by jamsch** [comment]
@abddeen Yep, that's due to the serialization of the `ExpoSpeechRecognitionResultList` /  `ExpoSpeechRecognitionResult` / `ExpoSpeechRecognitionAlternative` classes when you log in to the console. Those classes implement iterables and helpers (such as `.item(index)`) so that you can loop over them. The console logs that you got that showed `{}` meant that there wasn't any visible properties that can be serialized to the console, but you would have still been able to console log `event.results[event.resultIndex][0].transcript`.

**Comment by abddeen** [comment]
Ah yepp, that makes sense. It's all working as expected now. I've had to rejig my hook a little but this issue is fixed!
