### ISSUE TITLE
Retrieving cumulative transcript

### ISSUE THREAD

**Issue by danny188** [jamsch/expo-speech-recognition#31]
Hi @jamsch ,

I'm trying to create a cumulative transcript of words in continuous mode on Android. I noticed if the transcribed audio is for example "How are you", then the `result` event fires 3 times, with results being "How", "How are", and "How are you". Is this the expected behaviour?

Thanks.

**Comment by jamsch** [comment]
Hey @danny188, this is expected behavior when you enable interim results (interimResults setting when you call `.start()`) so that you can provide immediate feedback to the user when results come in. You can also distinguish between an interim result and a final result by checking the `event.isFinal` property in the "result" event.
