### ISSUE TITLE
`end` event fires if no speech detected for 10 seconds even in continuous mode?

### ISSUE THREAD

**Issue by danny188** [jamsch/expo-speech-recognition#32]
Hi,

Is there a way to keep the recording going even if no speech is detected for a few seconds? 

I find that the `end` event fires even in continuous mode after not speaking for about 10 seconds.

**Comment by jamsch** [comment]
Hey @danny188, the continuous mode is only currently supported for Android 13+ and iOS. It's not possible to do continuous recognition on older Android versions unfortunately due to an API limitation in the Android speech recognizer. You'll have to essentially do what you're doing which is to start the recognizer when it stops
